name: deploy next js concurrency

on:
 push:
   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy
      cancel-in-progress: true
    steps:
      - name: checkout reposittory
        uses: actions/checkout@v6.0.2
      - name: install dependency
        run: npm install
      - name: build next js
        run: npm run build
      - name: Deploy app 
        run: echo "deploting app........"
